name: Dependency review
on:
  pull_request:
permissions:
  contents: read
jobs:
  dependency-review:
    uses: rknightion/.github/.github/workflows/dependency-review.yml@e6d074e42fed0c74b1e9936637b7e2fb21403779 # v1.22.0
    permissions:
      contents: read
      pull-requests: write
